### ISSUE TITLE
Open Source the host code?

### ISSUE THREAD

**Issue by soulfresh** [MennoVink/FFGL_Testbed#3]
Would you be open to releasing the source for this project? I'd love to setup an FFGL plugin development sandbox with hot reload but all of the existing open source FFGL host projects are FFGL 1.5.

**Comment by MennoVink** [comment]
No sorry, that's not going to happen. This project actually comes from a huge codebase. It is built on top of my vulkan based graphics engine which is licensed commercially (ie to Resolume itself). When discussing licensing terms with Resolume we did talk about open source being a potential option. We've found that having the costs for the engine being open source vastly outweighs any potential benefit. We still wanted to offer this testbed for free though because it serves as a proof of concept for when Resolume moves over to vulkan. If ffgl works in this vulkan based testbed, then it will keep working in a vulkan based arena as well.

I've had the same idea as you to try and hotload plugins, but i couldn't get this to work robustly enough. The plugins are built into dynamic libraries, which need to be opened to use them. While those libraries are opened the linker wont be able to write to them anymore and thus you cant make changes. You could copy the libraries somewhere before opening, but some plugins ship with resources next to their library file so then those plugins wont work unless you know that and copy those resources too.
What i did to write the code that interacts with the plugin is look at the ffgl.h file, look at any interesting opcodes and then look at the ffgl.cpp file to see what kind of arguments it expects. It's a bit fiddly and trial and error but is possible.

**Comment by soulfresh** [comment]
Fair enough. Thanks for the detailed explanation.
